# Generated by Django 5.1 on 2025-11-11 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Dominos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='direccion_entrega',
            new_name='direccion',
        ),
    ]
