# Generated by Django 5.1 on 2025-11-11 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Dominos', '0002_rename_direccion_entrega_pedido_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='correo',
            new_name='email',
        ),
    ]
