# Generated by Django 5.1 on 2025-11-13 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Dominos', '0003_rename_correo_cliente_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tamaño', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=100)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='app_Dominos.cliente')),
            ],
        ),
    ]
